# -*- coding: utf-8 -*-
"""witnessing_article_select_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SdflXEipNHLZzDvjIAXx3_VBPjryK37l
"""

#import documents from local drive
#needed: contexts_final.xlsx

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
#import necessary libraries

import io
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

from wordcloud import WordCloud
from collections import Counter
from scipy.stats import pearsonr
from scipy.stats import ttest_ind

# %matplotlib inline

#transform documents to df and add IDs

contexts = pd.read_excel(io.BytesIO(uploaded['contexts_final.xlsx']))
contexts.zip.fillna(method='ffill', inplace=True)
contexts.docx.fillna(method='ffill', inplace=True)
contexts['ID'] = contexts['zip'] + ' ' + contexts['docx']

dictionary = ['zien', 'zie', 'kijken', 'keek', 'zagen', 'kijk', 'keken', 'zag', 'gekeken', 'gezien', 'horen', 'hoorde', 'hoorden', 'gehoord', 'luister', 'luisterde', 'luisterden', 'geluisterd', 'ruik', 'rook', 'geroken', 'roken', 'proef', 'proefde', 'geproefd', 'proefden', 'proeven', 'horen', 'luisteren', 'ruiken', 'voelen', 'gevoeld', 'voelde', 'voelden', 'tasten', 'tastte', 'tast', 'getast', 'aanraken', 'aangeraakt']

def data_select(data, dictionary):
  #create list of words that are present in the context data and are related to the category

  category_list = dictionary

  data['source:VERB'] = [data.loc[i, 'source:VERB'] if data.loc[i, 'nsubj'] in ['ik', 'wij', 'we'] else np.nan for i in data.index]

  # maak regex van de woordenlijst zodat de woorden in dataframe daaraan gematcht kunnen worden
  rgx_emo = r'\b(' + '|'.join(category_list) + r')\b'

  #check per sentence if there is one of the words
  interne_kopie = data.copy()
  interne_kopie['source:VERB'] = (interne_kopie['source:VERB'].str.match(rgx_emo)).astype('float')
  interne_kopie['emo_score'] = interne_kopie.loc[:, ['source:VERB']].sum(axis=1)

  #turn sentence scores into article scores
  data.text = data.text.fillna(method='ffill')
  sentence_data_IDS = interne_kopie[interne_kopie['emo_score'] > 0].index
  sentence_data = data[data.index.isin(sentence_data_IDS)]

  return sentence_data

#create word list, context data, metadata and sentence list for LIWC category 'affect'

wit_sentences = data_select(contexts, dictionary)

wit_sentences.to_excel('sensory_dataset.xlsx')

